services:
  cache:
    image: redis:6.2-alpine
    restart: always
#    ports:
#      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    volumes: 
      - ./cache:/data

  app:
    build: .
    container_name: party_billing_bot
    restart: "always"
    depends_on:
      - cache
    env_file:
      - .env
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
